# Generated by Django 5.0.7 on 2024-08-08 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='buy_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
